/* Auto-generated by scripts/sync-folder-product-variants.mjs. Do not edit manually. */
export interface AutoProductVariant {
  value: string;
  da: string;
  en: string;
  hex: string;
}

export const autoBybLadiesFluffySweatpantsVariants: AutoProductVariant[] = [
  {
    "value": "black",
    "da": "Sort",
    "en": "Black",
    "hex": "#111827"
  },
  {
    "value": "white",
    "da": "Hvid",
    "en": "White",
    "hex": "#F7F7F5"
  },
  {
    "value": "brown",
    "da": "Brun",
    "en": "Brown",
    "hex": "#8B6F57"
  },
  {
    "value": "light-asphalt",
    "da": "Light Asfalt",
    "en": "Light Asphalt",
    "hex": "#9CA3AF"
  },
  {
    "value": "soft-pink",
    "da": "Soft Pink",
    "en": "Soft Pink",
    "hex": "#F3CBD8"
  },
  {
    "value": "grey",
    "da": "Grå",
    "en": "Grey",
    "hex": "#9CA3AF"
  }
];

export const autoBybLadiesFluffySweatpantsColorMockups: Record<string, Partial<Record<"fullFront" | "leftSleeve" | "rightSleeve" | "fullBack", string>>> = {
  "brown": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-brown-front.webp",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-brown-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-brown-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-brown-back.webp"
  },
  "grey": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-grey-front.jpg",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-grey-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-grey-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-grey-back.jpg"
  },
  "white": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-white-front.webp",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-white-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-white-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-white-back.webp"
  },
  "light-asphalt": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-light-asphalt-front.webp",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-light-asphalt-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-light-asphalt-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-light-asphalt-back.webp"
  },
  "soft-pink": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-soft-pink-front.webp",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-soft-pink-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-soft-pink-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-soft-pink-back.webp"
  },
  "black": {
    "fullFront": "/byb-ladies-fluffy-sweatpants-black-front.webp",
    "leftSleeve": "/byb-ladies-fluffy-sweatpants-black-left.jpg",
    "rightSleeve": "/byb-ladies-fluffy-sweatpants-black-left.jpg",
    "fullBack": "/byb-ladies-fluffy-sweatpants-black-back.webp"
  }
};

export const autoBybLadiesFluffySweatpantsCardImages: { front: string; back: string } | null = {
  "front": "/byb-ladies-fluffy-sweatpants-black-front.webp",
  "back": "/byb-ladies-fluffy-sweatpants-black-back.webp"
};
