/* Auto-generated by scripts/sync-tshirt-variants.mjs. Do not edit manually. */
export interface AutoProductVariant {
  value: string;
  da: string;
  en: string;
  hex: string;
}

export const autoBasicTshirtVariants: AutoProductVariant[] = [
  {
    "value": "white",
    "da": "Hvid",
    "en": "White",
    "hex": "#F7F7F5"
  },
  {
    "value": "black",
    "da": "Sort",
    "en": "Black",
    "hex": "#1C1C1C"
  },
  {
    "value": "french-navy",
    "da": "French Navy",
    "en": "French Navy",
    "hex": "#3B4557"
  },
  {
    "value": "classic-red",
    "da": "Classic Red",
    "en": "Classic Red",
    "hex": "#D92247"
  },
  {
    "value": "bright-royal",
    "da": "Azur blå",
    "en": "Azure Blue",
    "hex": "#6C8CB0"
  },
  {
    "value": "bottle-green",
    "da": "Oliven",
    "en": "Olive",
    "hex": "#3F6B5A"
  },
  {
    "value": "convoy-grey",
    "da": "Convoy Grey",
    "en": "Convoy Grey",
    "hex": "#6B7280"
  },
  {
    "value": "sky",
    "da": "Sky",
    "en": "Sky",
    "hex": "#74B9E6"
  },
  {
    "value": "purple",
    "da": "Lilla",
    "en": "Purple",
    "hex": "#8574A5"
  },
  {
    "value": "burgundy",
    "da": "Bordeaux",
    "en": "Burgundy",
    "hex": "#A2535F"
  },
  {
    "value": "yellow",
    "da": "Gul",
    "en": "Yellow",
    "hex": "#FFE100"
  },
  {
    "value": "tan",
    "da": "Tan",
    "en": "Tan",
    "hex": "#C19A6B"
  },
  {
    "value": "light-oxford",
    "da": "Light Oxford",
    "en": "Light Oxford",
    "hex": "#CBD5E1"
  },
  {
    "value": "mineral-blue",
    "da": "Mineral blå",
    "en": "Mineral Blue",
    "hex": "#5C7A9C"
  },
  {
    "value": "mocha",
    "da": "Mocha",
    "en": "Mocha",
    "hex": "#8B6F57"
  },
  {
    "value": "natural",
    "da": "Natur",
    "en": "Natural",
    "hex": "#D8CFB8"
  },
  {
    "value": "rose",
    "da": "Rose",
    "en": "Rose",
    "hex": "#C98EA5"
  }
];

export const autoBasicTshirtColorMockups: Record<string, Partial<Record<"fullFront" | "leftSleeve" | "rightSleeve" | "fullBack", string>>> = {
  "bright-royal": {
    "fullFront": "/russell-bright-royal-front.jpg",
    "leftSleeve": "/russell-bright-royal-left-sleeve.jpg",
    "rightSleeve": "/russell-bright-royal-right-sleeve.jpg",
    "fullBack": "/russell-bright-royal-back.jpg"
  },
  "burgundy": {
    "fullFront": "/russell-burgundy-front.jpg",
    "leftSleeve": "/russell-burgundy-left-sleeve.jpg",
    "rightSleeve": "/russell-burgundy-right-sleeve.jpg",
    "fullBack": "/russell-burgundy-back.jpg"
  },
  "classic-red": {
    "fullFront": "/russell-classic-red-front.jpg",
    "leftSleeve": "/russell-classic-red-left-sleeve.jpg",
    "rightSleeve": "/russell-classic-red-right-sleeve.jpg",
    "fullBack": "/russell-classic-red-back.jpg"
  },
  "convoy-grey": {
    "fullFront": "/russell-convoy-grey-front.jpg",
    "leftSleeve": "/russell-convoy-grey-left-sleeve.jpg",
    "rightSleeve": "/russell-convoy-grey-right-sleeve.jpg",
    "fullBack": "/russell-convoy-grey-back.jpg"
  },
  "french-navy": {
    "fullFront": "/russell-french-navy-front.jpg",
    "leftSleeve": "/russell-french-navy-left-sleeve.jpg",
    "rightSleeve": "/russell-french-navy-right-sleeve.jpg",
    "fullBack": "/russell-french-navy-back.jpg"
  },
  "yellow": {
    "fullFront": "/russell-yellow-front.jpg",
    "leftSleeve": "/russell-yellow-left-sleeve.jpg",
    "rightSleeve": "/russell-yellow-right-sleeve.jpg",
    "fullBack": "/russell-yellow-back.jpg"
  },
  "white": {
    "fullFront": "/russell-white-front.jpg",
    "leftSleeve": "/russell-white-left-sleeve.jpg",
    "rightSleeve": "/russell-white-right-sleeve.jpg",
    "fullBack": "/russell-white-back.jpg"
  },
  "light-oxford": {
    "fullFront": "/russell-light-oxford-front.jpg",
    "leftSleeve": "/russell-light-oxford-left-sleeve.jpg",
    "rightSleeve": "/russell-light-oxford-right-sleeve.jpg",
    "fullBack": "/russell-light-oxford-back.jpg"
  },
  "purple": {
    "fullFront": "/russell-purple-front.jpg",
    "leftSleeve": "/russell-purple-left-sleeve.jpg",
    "rightSleeve": "/russell-purple-right-sleeve.jpg",
    "fullBack": "/russell-purple-back.jpg"
  },
  "mineral-blue": {
    "fullFront": "/russell-mineral-blue-front.jpg",
    "leftSleeve": "/russell-mineral-blue-left-sleeve.jpg",
    "rightSleeve": "/russell-mineral-blue-right-sleeve.jpg",
    "fullBack": "/russell-mineral-blue-back.jpg"
  },
  "mocha": {
    "fullFront": "/russell-mocha-front.jpg",
    "leftSleeve": "/russell-mocha-left-sleeve.jpg",
    "rightSleeve": "/russell-mocha-right-sleeve.jpg",
    "fullBack": "/russell-mocha-back.jpg"
  },
  "natural": {
    "fullFront": "/russell-natural-front.jpg",
    "leftSleeve": "/russell-natural-left-sleeve.jpg",
    "rightSleeve": "/russell-natural-right-sleeve.jpg",
    "fullBack": "/russell-natural-back.jpg"
  },
  "bottle-green": {
    "fullFront": "/russell-bottle-green-front.jpg",
    "leftSleeve": "/russell-bottle-green-left-sleeve.jpg",
    "rightSleeve": "/russell-bottle-green-right-sleeve.jpg",
    "fullBack": "/russell-bottle-green-back.jpg"
  },
  "rose": {
    "fullFront": "/russell-rose-front.jpg",
    "leftSleeve": "/russell-rose-left-sleeve.jpg",
    "rightSleeve": "/russell-rose-right-sleeve.jpg",
    "fullBack": "/russell-rose-back.jpg"
  },
  "sky": {
    "fullFront": "/russell-sky-front.jpg",
    "leftSleeve": "/russell-sky-left-sleeve.jpg",
    "rightSleeve": "/russell-sky-right-sleeve.jpg",
    "fullBack": "/russell-sky-back.jpg"
  },
  "black": {
    "fullFront": "/russell-black-front.jpg",
    "leftSleeve": "/russell-black-left-sleeve.jpg",
    "rightSleeve": "/russell-black-right-sleeve.jpg",
    "fullBack": "/russell-black-back.jpg"
  },
  "tan": {
    "fullFront": "/russell-tan-front.jpg",
    "leftSleeve": "/russell-tan-left-sleeve.jpg",
    "rightSleeve": "/russell-tan-right-sleeve.jpg",
    "fullBack": "/russell-tan-back.jpg"
  }
};

export const autoPerformanceTshirtVariants: AutoProductVariant[] = [
  {
    "value": "white",
    "da": "Hvid",
    "en": "White",
    "hex": "#F7F7F5"
  },
  {
    "value": "black",
    "da": "Sort",
    "en": "Black",
    "hex": "#1C1C1C"
  },
  {
    "value": "royal-blue",
    "da": "Royal Blue",
    "en": "Royal Blue",
    "hex": "#2563EB"
  },
  {
    "value": "sapphire-blue",
    "da": "Sapphire Blue",
    "en": "Sapphire Blue",
    "hex": "#1E3A8A"
  },
  {
    "value": "silver-melange",
    "da": "Silver Malange",
    "en": "Silver Melange",
    "hex": "#94A3B8"
  },
  {
    "value": "turquoise",
    "da": "Turquoise",
    "en": "Turquoise",
    "hex": "#14B8A6"
  },
  {
    "value": "blue-steel",
    "da": "Blue Steel",
    "en": "Blue Steel",
    "hex": "#5B6E80"
  },
  {
    "value": "bright-green",
    "da": "Bright Green",
    "en": "Bright Green",
    "hex": "#42B883"
  },
  {
    "value": "bright-purple",
    "da": "Bright Purple",
    "en": "Bright Purple",
    "hex": "#7A4FB7"
  },
  {
    "value": "french-navy",
    "da": "French Navy",
    "en": "French Navy",
    "hex": "#3B4557"
  },
  {
    "value": "bottle-green",
    "da": "Oliven",
    "en": "Olive",
    "hex": "#3F6B5A"
  },
  {
    "value": "burgundy",
    "da": "Bordeaux",
    "en": "Burgundy",
    "hex": "#A2535F"
  },
  {
    "value": "yellow",
    "da": "Gul",
    "en": "Yellow",
    "hex": "#FFE100"
  },
  {
    "value": "blue-malange",
    "da": "Blue Malange",
    "en": "Blue Malange",
    "hex": "#9CA3AF"
  },
  {
    "value": "neon-green",
    "da": "Neon Green",
    "en": "Neon Green",
    "hex": "#9CA3AF"
  },
  {
    "value": "neon-orange",
    "da": "Neon Orange",
    "en": "Neon Orange",
    "hex": "#9CA3AF"
  },
  {
    "value": "neon-yellow",
    "da": "Neon Yellow",
    "en": "Neon Yellow",
    "hex": "#9CA3AF"
  },
  {
    "value": "orange",
    "da": "Orange",
    "en": "Orange",
    "hex": "#9CA3AF"
  }
];

export const autoPerformanceTshirtColorMockups: Record<string, Partial<Record<"fullFront" | "leftSleeve" | "rightSleeve" | "fullBack", string>>> = {
  "blue-malange": {
    "fullFront": "/tridri-performance-blue-malange-front.png",
    "leftSleeve": "/tridri-performance-blue-malange-left-sleeve.png",
    "rightSleeve": "/tridri-performance-blue-malange-right-sleeve.png",
    "fullBack": "/tridri-performance-blue-malange-back.png"
  },
  "blue-steel": {
    "fullFront": "/tridri-performance-blue-steel-front.png",
    "leftSleeve": "/tridri-performance-blue-steel-left-sleeve.png",
    "rightSleeve": "/tridri-performance-blue-steel-right-sleeve.png",
    "fullBack": "/tridri-performance-blue-steel-back.png"
  },
  "burgundy": {
    "fullFront": "/tridri-performance-burgundy-front.png",
    "leftSleeve": "/tridri-performance-burgundy-left-sleeve.png",
    "rightSleeve": "/tridri-performance-burgundy-right-sleeve.png",
    "fullBack": "/tridri-performance-burgundy-back.png"
  },
  "bright-green": {
    "fullFront": "/tridri-performance-bright-green-front.png",
    "leftSleeve": "/tridri-performance-bright-green-left-sleeve.png",
    "rightSleeve": "/tridri-performance-bright-green-right-sleeve.png",
    "fullBack": "/tridri-performance-bright-green-back.png"
  },
  "bright-purple": {
    "fullFront": "/tridri-performance-bright-purple-front.png",
    "leftSleeve": "/tridri-performance-bright-purple-left-sleeve.png",
    "rightSleeve": "/tridri-performance-bright-purple-right-sleeve.png",
    "fullBack": "/tridri-performance-bright-purple-back.png"
  },
  "french-navy": {
    "fullFront": "/tridri-performance-french-navy-front.png",
    "leftSleeve": "/tridri-performance-french-navy-left-sleeve.png",
    "rightSleeve": "/tridri-performance-french-navy-right-sleeve.png",
    "fullBack": "/tridri-performance-french-navy-back.png"
  },
  "yellow": {
    "fullFront": "/tridri-performance-yellow-front.png",
    "leftSleeve": "/tridri-performance-yellow-left-sleeve.png",
    "rightSleeve": "/tridri-performance-yellow-right-sleeve.png",
    "fullBack": "/tridri-performance-yellow-back.png"
  },
  "white": {
    "fullFront": "/tridri-performance-white-front.png",
    "leftSleeve": "/tridri-performance-white-left-sleeve.png",
    "rightSleeve": "/tridri-performance-white-right-sleeve.png",
    "fullBack": "/tridri-performance-white-back.png"
  },
  "neon-green": {
    "fullFront": "/tridri-performance-neon-green-front.png",
    "leftSleeve": "/tridri-performance-neon-green-left-sleeve.png",
    "rightSleeve": "/tridri-performance-neon-green-right-sleeve.png",
    "fullBack": "/tridri-performance-neon-green-back.png"
  },
  "neon-orange": {
    "fullFront": "/tridri-performance-neon-orange-front.png",
    "leftSleeve": "/tridri-performance-neon-orange-left-sleeve.png",
    "rightSleeve": "/tridri-performance-neon-orange-right-sleeve.png",
    "fullBack": "/tridri-performance-neon-orange-back.png"
  },
  "neon-yellow": {
    "fullFront": "/tridri-performance-neon-yellow-front.png",
    "leftSleeve": "/tridri-performance-neon-yellow-left-sleeve.png",
    "rightSleeve": "/tridri-performance-neon-yellow-right-sleeve.png",
    "fullBack": "/tridri-performance-neon-yellow-back.png"
  },
  "bottle-green": {
    "fullFront": "/tridri-performance-bottle-green-front.png",
    "leftSleeve": "/tridri-performance-bottle-green-left-sleeve.png",
    "rightSleeve": "/tridri-performance-bottle-green-right-sleeve.png",
    "fullBack": "/tridri-performance-bottle-green-back.png"
  },
  "orange": {
    "fullFront": "/tridri-performance-orange-front.png",
    "leftSleeve": "/tridri-performance-orange-left-sleeve.png",
    "rightSleeve": "/tridri-performance-orange-right-sleeve.png",
    "fullBack": "/tridri-performance-orange-back.png"
  },
  "royal-blue": {
    "fullFront": "/tridri-performance-royal-blue-front.png",
    "leftSleeve": "/tridri-performance-royal-blue-left-sleeve.png",
    "rightSleeve": "/tridri-performance-royal-blue-right-sleeve.png",
    "fullBack": "/tridri-performance-royal-blue-back.png"
  },
  "sapphire-blue": {
    "fullFront": "/tridri-performance-sapphire-blue-front.png",
    "leftSleeve": "/tridri-performance-sapphire-blue-left-sleeve.png",
    "rightSleeve": "/tridri-performance-sapphire-blue-right-sleeve.png",
    "fullBack": "/tridri-performance-sapphire-blue-back.png"
  },
  "silver-melange": {
    "fullFront": "/tridri-performance-silver-melange-front.png",
    "leftSleeve": "/tridri-performance-silver-melange-left-sleeve.png",
    "rightSleeve": "/tridri-performance-silver-melange-right-sleeve.png",
    "fullBack": "/tridri-performance-silver-melange-back.png"
  },
  "black": {
    "fullFront": "/tridri-performance-black-front.png",
    "leftSleeve": "/tridri-performance-black-left-sleeve.png",
    "rightSleeve": "/tridri-performance-black-right-sleeve.png",
    "fullBack": "/tridri-performance-black-back.png"
  },
  "turquoise": {
    "fullFront": "/tridri-performance-turquoise-front.png",
    "leftSleeve": "/tridri-performance-turquoise-left-sleeve.png",
    "rightSleeve": "/tridri-performance-turquoise-right-sleeve.png",
    "fullBack": "/tridri-performance-turquoise-back.png"
  }
};

export const autoPremiumHoodieVariants: AutoProductVariant[] = [
  {
    "value": "white",
    "da": "Hvid",
    "en": "White",
    "hex": "#F7F7F5"
  },
  {
    "value": "black",
    "da": "Sort",
    "en": "Black",
    "hex": "#1C1C1C"
  },
  {
    "value": "french-navy",
    "da": "French Navy",
    "en": "French Navy",
    "hex": "#3B4557"
  },
  {
    "value": "classic-red",
    "da": "Classic Red",
    "en": "Classic Red",
    "hex": "#D92247"
  },
  {
    "value": "bright-royal",
    "da": "Azur blå",
    "en": "Azure Blue",
    "hex": "#6C8CB0"
  },
  {
    "value": "bottle-green",
    "da": "Oliven",
    "en": "Olive",
    "hex": "#3F6B5A"
  },
  {
    "value": "convoy-grey",
    "da": "Convoy Grey",
    "en": "Convoy Grey",
    "hex": "#6B7280"
  },
  {
    "value": "burgundy",
    "da": "Bordeaux",
    "en": "Burgundy",
    "hex": "#A2535F"
  },
  {
    "value": "yellow",
    "da": "Gul",
    "en": "Yellow",
    "hex": "#FFE100"
  },
  {
    "value": "mineral-blue",
    "da": "Mineral blå",
    "en": "Mineral Blue",
    "hex": "#5C7A9C"
  },
  {
    "value": "mocha",
    "da": "Mocha",
    "en": "Mocha",
    "hex": "#8B6F57"
  },
  {
    "value": "natural",
    "da": "Natur",
    "en": "Natural",
    "hex": "#D8CFB8"
  },
  {
    "value": "pink",
    "da": "Pink",
    "en": "Pink",
    "hex": "#D38DA5"
  },
  {
    "value": "oxford-grey",
    "da": "Oxford Grey",
    "en": "Oxford Grey",
    "hex": "#9CA3AF"
  }
];

export const autoPremiumHoodieColorMockups: Record<string, Partial<Record<"fullFront" | "leftSleeve" | "rightSleeve" | "fullBack", string>>> = {
  "bright-royal": {
    "fullFront": "/russell-premium-hoodie-bright-royal-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-bright-royal-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-bright-royal-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-bright-royal-back.jpg"
  },
  "burgundy": {
    "fullFront": "/russell-premium-hoodie-burgundy-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-burgundy-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-burgundy-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-burgundy-back.jpg"
  },
  "classic-red": {
    "fullFront": "/russell-premium-hoodie-classic-red-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-classic-red-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-classic-red-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-classic-red-back.jpg"
  },
  "convoy-grey": {
    "fullFront": "/russell-premium-hoodie-convoy-grey-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-convoy-grey-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-convoy-grey-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-convoy-grey-back.jpg"
  },
  "french-navy": {
    "fullFront": "/russell-premium-hoodie-french-navy-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-french-navy-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-french-navy-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-french-navy-back.jpg"
  },
  "yellow": {
    "fullFront": "/russell-premium-hoodie-yellow-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-yellow-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-yellow-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-yellow-back.jpg"
  },
  "white": {
    "fullFront": "/russell-premium-hoodie-white-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-white-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-white-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-white-back.jpg"
  },
  "mineral-blue": {
    "fullFront": "/russell-premium-hoodie-mineral-blue-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-mineral-blue-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-mineral-blue-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-mineral-blue-back.jpg"
  },
  "mocha": {
    "fullFront": "/russell-premium-hoodie-mocha-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-mocha-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-mocha-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-mocha-back.jpg"
  },
  "natural": {
    "fullFront": "/russell-premium-hoodie-natural-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-natural-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-natural-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-natural-back.jpg"
  },
  "bottle-green": {
    "fullFront": "/russell-premium-hoodie-bottle-green-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-bottle-green-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-bottle-green-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-bottle-green-back.jpg"
  },
  "oxford-grey": {
    "fullFront": "/russell-premium-hoodie-oxford-grey-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-oxford-grey-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-oxford-grey-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-oxford-grey-back.jpg"
  },
  "pink": {
    "fullFront": "/russell-premium-hoodie-pink-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-pink-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-pink-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-pink-back.jpg"
  },
  "black": {
    "fullFront": "/russell-premium-hoodie-black-front.jpg",
    "leftSleeve": "/russell-premium-hoodie-black-left-sleeve.jpg",
    "rightSleeve": "/russell-premium-hoodie-black-right-sleeve.jpg",
    "fullBack": "/russell-premium-hoodie-black-back.jpg"
  }
};

export const autoStandardHoodieVariants: AutoProductVariant[] = [
  {
    "value": "white",
    "da": "Hvid",
    "en": "White",
    "hex": "#F7F7F5"
  },
  {
    "value": "black",
    "da": "Sort",
    "en": "Black",
    "hex": "#1C1C1C"
  },
  {
    "value": "french-navy",
    "da": "French Navy",
    "en": "French Navy",
    "hex": "#3B4557"
  },
  {
    "value": "classic-red",
    "da": "Classic Red",
    "en": "Classic Red",
    "hex": "#D92247"
  },
  {
    "value": "bright-royal",
    "da": "Azur blå",
    "en": "Azure Blue",
    "hex": "#6C8CB0"
  },
  {
    "value": "bottle-green",
    "da": "Oliven",
    "en": "Olive",
    "hex": "#3F6B5A"
  },
  {
    "value": "burgundy",
    "da": "Bordeaux",
    "en": "Burgundy",
    "hex": "#A2535F"
  },
  {
    "value": "yellow",
    "da": "Gul",
    "en": "Yellow",
    "hex": "#FFE100"
  },
  {
    "value": "pink",
    "da": "Pink",
    "en": "Pink",
    "hex": "#D38DA5"
  },
  {
    "value": "oxford-grey",
    "da": "Oxford Grey",
    "en": "Oxford Grey",
    "hex": "#9CA3AF"
  }
];

export const autoStandardHoodieColorMockups: Record<string, Partial<Record<"fullFront" | "leftSleeve" | "rightSleeve" | "fullBack", string>>> = {
  "bright-royal": {
    "fullFront": "/russell-basic-hoodie-bright-royal-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-bright-royal-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-bright-royal-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-bright-royal-back.jpg"
  },
  "burgundy": {
    "fullFront": "/russell-basic-hoodie-burgundy-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-burgundy-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-burgundy-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-burgundy-back.jpg"
  },
  "classic-red": {
    "fullFront": "/russell-basic-hoodie-classic-red-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-classic-red-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-classic-red-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-classic-red-back.jpg"
  },
  "french-navy": {
    "fullFront": "/russell-basic-hoodie-french-navy-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-french-navy-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-french-navy-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-french-navy-back.jpg"
  },
  "yellow": {
    "fullFront": "/russell-basic-hoodie-yellow-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-yellow-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-yellow-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-yellow-back.jpg"
  },
  "white": {
    "fullFront": "/russell-basic-hoodie-white-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-white-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-white-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-white-back.jpg"
  },
  "bottle-green": {
    "fullFront": "/russell-basic-hoodie-bottle-green-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-bottle-green-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-bottle-green-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-bottle-green-back.jpg"
  },
  "oxford-grey": {
    "fullFront": "/russell-basic-hoodie-oxford-grey-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-oxford-grey-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-oxford-grey-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-oxford-grey-back.jpg"
  },
  "pink": {
    "fullFront": "/russell-basic-hoodie-pink-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-pink-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-pink-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-pink-back.jpg"
  },
  "black": {
    "fullFront": "/russell-basic-hoodie-black-front.jpg",
    "leftSleeve": "/russell-basic-hoodie-black-left-sleeve.jpg",
    "rightSleeve": "/russell-basic-hoodie-black-right-sleeve.jpg",
    "fullBack": "/russell-basic-hoodie-black-back.jpg"
  }
};
